apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: angular-app
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/fe-yoga-pose-default: "true"
        io.kompose.service: angular-app
    spec:
      containers:
        - image: gcr.io/yoga-pose-406917/fe-yoga-pose:v2
          name: angular-app
          ports:
            - containerPort: 80
              hostPort: 4200
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
